// <auto-generated />
namespace Canalot.Extensions;

public static partial class CanalotExtensions
{
    // 单值 Apply 手写 (Func)
    /// <summary>
    /// 将单个值传入函数
    /// </summary>
    /// <typeparam name="T">值的类型</typeparam>
    /// <typeparam name="TResult">返回值类型</typeparam>
    /// <param name="value">要传入的值</param>
    /// <param name="func">接收一个参数的函数</param>
    /// <returns>函数返回值</returns>
    public static TResult Apply<T, TResult>(this T value, Func<T, TResult> func)
    {
        return func(value);
    }

    // 单值 Apply (Action) - 返回自身
    /// <summary>
    /// 将单个值传入无返回值的方法，并返回原值
    /// </summary>
    /// <typeparam name="T">值的类型</typeparam>
    /// <param name="value">要传入的值</param>
    /// <param name="action">接收一个参数的无返回值方法</param>
    /// <returns>原值本身，便于链式调用</returns>
    public static T Apply<T>(this T value, Action<T> action)
    {
        action(value);
        return value;
    }

    /// <summary>
    /// 将二元组解构后传入函数 (有返回值)
    /// </summary>
    /// <typeparam name="T1">第1个元素的类型</typeparam>
    /// <typeparam name="T2">第2个元素的类型</typeparam>
    /// <typeparam name="TResult">返回值类型</typeparam>
    /// <param name="value">要解构的 2 元组</param>
    /// <param name="func">接收 2 个参数的函数</param>
    /// <returns>函数返回值</returns>
    public static TResult Apply<T1, T2, TResult>(this (T1, T2) value, Func<T1, T2, TResult> func)
    {
        return func(value.Item1, value.Item2);
    }

    /// <summary>
    /// 将二元组解构后传入函数 (无返回值，返回原元组)
    /// </summary>
    /// <typeparam name="T1">第1个元素的类型</typeparam>
    /// <typeparam name="T2">第2个元素的类型</typeparam>
    /// <param name="value">要解构的 2 元组</param>
    /// <param name="action">接收 2 个参数的无返回值方法</param>
    /// <returns>原元组本身，便于链式调用</returns>
    public static (T1, T2) Apply<T1, T2>(this (T1, T2) value, Action<T1, T2> action)
    {
        action(value.Item1, value.Item2);
        return value;
    }

    /// <summary>
    /// 将3元组解构后传入函数 (有返回值)
    /// </summary>
    /// <typeparam name="T1">第1个元素的类型</typeparam>
    /// <typeparam name="T2">第2个元素的类型</typeparam>
    /// <typeparam name="T3">第3个元素的类型</typeparam>
    /// <typeparam name="TResult">返回值类型</typeparam>
    /// <param name="value">要解构的 3 元组</param>
    /// <param name="func">接收 3 个参数的函数</param>
    /// <returns>函数返回值</returns>
    public static TResult Apply<T1, T2, T3, TResult>(this (T1, T2, T3) value, Func<T1, T2, T3, TResult> func)
    {
        return func(value.Item1, value.Item2, value.Item3);
    }

    /// <summary>
    /// 将3元组解构后传入函数 (无返回值，返回原元组)
    /// </summary>
    /// <typeparam name="T1">第1个元素的类型</typeparam>
    /// <typeparam name="T2">第2个元素的类型</typeparam>
    /// <typeparam name="T3">第3个元素的类型</typeparam>
    /// <param name="value">要解构的 3 元组</param>
    /// <param name="action">接收 3 个参数的无返回值方法</param>
    /// <returns>原元组本身，便于链式调用</returns>
    public static (T1, T2, T3) Apply<T1, T2, T3>(this (T1, T2, T3) value, Action<T1, T2, T3> action)
    {
        action(value.Item1, value.Item2, value.Item3);
        return value;
    }

    /// <summary>
    /// 将4元组解构后传入函数 (有返回值)
    /// </summary>
    /// <typeparam name="T1">第1个元素的类型</typeparam>
    /// <typeparam name="T2">第2个元素的类型</typeparam>
    /// <typeparam name="T3">第3个元素的类型</typeparam>
    /// <typeparam name="T4">第4个元素的类型</typeparam>
    /// <typeparam name="TResult">返回值类型</typeparam>
    /// <param name="value">要解构的 4 元组</param>
    /// <param name="func">接收 4 个参数的函数</param>
    /// <returns>函数返回值</returns>
    public static TResult Apply<T1, T2, T3, T4, TResult>(this (T1, T2, T3, T4) value, Func<T1, T2, T3, T4, TResult> func)
    {
        return func(value.Item1, value.Item2, value.Item3, value.Item4);
    }

    /// <summary>
    /// 将4元组解构后传入函数 (无返回值，返回原元组)
    /// </summary>
    /// <typeparam name="T1">第1个元素的类型</typeparam>
    /// <typeparam name="T2">第2个元素的类型</typeparam>
    /// <typeparam name="T3">第3个元素的类型</typeparam>
    /// <typeparam name="T4">第4个元素的类型</typeparam>
    /// <param name="value">要解构的 4 元组</param>
    /// <param name="action">接收 4 个参数的无返回值方法</param>
    /// <returns>原元组本身，便于链式调用</returns>
    public static (T1, T2, T3, T4) Apply<T1, T2, T3, T4>(this (T1, T2, T3, T4) value, Action<T1, T2, T3, T4> action)
    {
        action(value.Item1, value.Item2, value.Item3, value.Item4);
        return value;
    }

    /// <summary>
    /// 将5元组解构后传入函数 (有返回值)
    /// </summary>
    /// <typeparam name="T1">第1个元素的类型</typeparam>
    /// <typeparam name="T2">第2个元素的类型</typeparam>
    /// <typeparam name="T3">第3个元素的类型</typeparam>
    /// <typeparam name="T4">第4个元素的类型</typeparam>
    /// <typeparam name="T5">第5个元素的类型</typeparam>
    /// <typeparam name="TResult">返回值类型</typeparam>
    /// <param name="value">要解构的 5 元组</param>
    /// <param name="func">接收 5 个参数的函数</param>
    /// <returns>函数返回值</returns>
    public static TResult Apply<T1, T2, T3, T4, T5, TResult>(this (T1, T2, T3, T4, T5) value, Func<T1, T2, T3, T4, T5, TResult> func)
    {
        return func(value.Item1, value.Item2, value.Item3, value.Item4, value.Item5);
    }

    /// <summary>
    /// 将5元组解构后传入函数 (无返回值，返回原元组)
    /// </summary>
    /// <typeparam name="T1">第1个元素的类型</typeparam>
    /// <typeparam name="T2">第2个元素的类型</typeparam>
    /// <typeparam name="T3">第3个元素的类型</typeparam>
    /// <typeparam name="T4">第4个元素的类型</typeparam>
    /// <typeparam name="T5">第5个元素的类型</typeparam>
    /// <param name="value">要解构的 5 元组</param>
    /// <param name="action">接收 5 个参数的无返回值方法</param>
    /// <returns>原元组本身，便于链式调用</returns>
    public static (T1, T2, T3, T4, T5) Apply<T1, T2, T3, T4, T5>(this (T1, T2, T3, T4, T5) value, Action<T1, T2, T3, T4, T5> action)
    {
        action(value.Item1, value.Item2, value.Item3, value.Item4, value.Item5);
        return value;
    }

    /// <summary>
    /// 将6元组解构后传入函数 (有返回值)
    /// </summary>
    /// <typeparam name="T1">第1个元素的类型</typeparam>
    /// <typeparam name="T2">第2个元素的类型</typeparam>
    /// <typeparam name="T3">第3个元素的类型</typeparam>
    /// <typeparam name="T4">第4个元素的类型</typeparam>
    /// <typeparam name="T5">第5个元素的类型</typeparam>
    /// <typeparam name="T6">第6个元素的类型</typeparam>
    /// <typeparam name="TResult">返回值类型</typeparam>
    /// <param name="value">要解构的 6 元组</param>
    /// <param name="func">接收 6 个参数的函数</param>
    /// <returns>函数返回值</returns>
    public static TResult Apply<T1, T2, T3, T4, T5, T6, TResult>(this (T1, T2, T3, T4, T5, T6) value, Func<T1, T2, T3, T4, T5, T6, TResult> func)
    {
        return func(value.Item1, value.Item2, value.Item3, value.Item4, value.Item5, value.Item6);
    }

    /// <summary>
    /// 将6元组解构后传入函数 (无返回值，返回原元组)
    /// </summary>
    /// <typeparam name="T1">第1个元素的类型</typeparam>
    /// <typeparam name="T2">第2个元素的类型</typeparam>
    /// <typeparam name="T3">第3个元素的类型</typeparam>
    /// <typeparam name="T4">第4个元素的类型</typeparam>
    /// <typeparam name="T5">第5个元素的类型</typeparam>
    /// <typeparam name="T6">第6个元素的类型</typeparam>
    /// <param name="value">要解构的 6 元组</param>
    /// <param name="action">接收 6 个参数的无返回值方法</param>
    /// <returns>原元组本身，便于链式调用</returns>
    public static (T1, T2, T3, T4, T5, T6) Apply<T1, T2, T3, T4, T5, T6>(this (T1, T2, T3, T4, T5, T6) value, Action<T1, T2, T3, T4, T5, T6> action)
    {
        action(value.Item1, value.Item2, value.Item3, value.Item4, value.Item5, value.Item6);
        return value;
    }

    /// <summary>
    /// 将7元组解构后传入函数 (有返回值)
    /// </summary>
    /// <typeparam name="T1">第1个元素的类型</typeparam>
    /// <typeparam name="T2">第2个元素的类型</typeparam>
    /// <typeparam name="T3">第3个元素的类型</typeparam>
    /// <typeparam name="T4">第4个元素的类型</typeparam>
    /// <typeparam name="T5">第5个元素的类型</typeparam>
    /// <typeparam name="T6">第6个元素的类型</typeparam>
    /// <typeparam name="T7">第7个元素的类型</typeparam>
    /// <typeparam name="TResult">返回值类型</typeparam>
    /// <param name="value">要解构的 7 元组</param>
    /// <param name="func">接收 7 个参数的函数</param>
    /// <returns>函数返回值</returns>
    public static TResult Apply<T1, T2, T3, T4, T5, T6, T7, TResult>(this (T1, T2, T3, T4, T5, T6, T7) value, Func<T1, T2, T3, T4, T5, T6, T7, TResult> func)
    {
        return func(value.Item1, value.Item2, value.Item3, value.Item4, value.Item5, value.Item6, value.Item7);
    }

    /// <summary>
    /// 将7元组解构后传入函数 (无返回值，返回原元组)
    /// </summary>
    /// <typeparam name="T1">第1个元素的类型</typeparam>
    /// <typeparam name="T2">第2个元素的类型</typeparam>
    /// <typeparam name="T3">第3个元素的类型</typeparam>
    /// <typeparam name="T4">第4个元素的类型</typeparam>
    /// <typeparam name="T5">第5个元素的类型</typeparam>
    /// <typeparam name="T6">第6个元素的类型</typeparam>
    /// <typeparam name="T7">第7个元素的类型</typeparam>
    /// <param name="value">要解构的 7 元组</param>
    /// <param name="action">接收 7 个参数的无返回值方法</param>
    /// <returns>原元组本身，便于链式调用</returns>
    public static (T1, T2, T3, T4, T5, T6, T7) Apply<T1, T2, T3, T4, T5, T6, T7>(this (T1, T2, T3, T4, T5, T6, T7) value, Action<T1, T2, T3, T4, T5, T6, T7> action)
    {
        action(value.Item1, value.Item2, value.Item3, value.Item4, value.Item5, value.Item6, value.Item7);
        return value;
    }

    /// <summary>
    /// 将8元组解构后传入函数 (有返回值)
    /// </summary>
    /// <typeparam name="T1">第1个元素的类型</typeparam>
    /// <typeparam name="T2">第2个元素的类型</typeparam>
    /// <typeparam name="T3">第3个元素的类型</typeparam>
    /// <typeparam name="T4">第4个元素的类型</typeparam>
    /// <typeparam name="T5">第5个元素的类型</typeparam>
    /// <typeparam name="T6">第6个元素的类型</typeparam>
    /// <typeparam name="T7">第7个元素的类型</typeparam>
    /// <typeparam name="T8">第8个元素的类型</typeparam>
    /// <typeparam name="TResult">返回值类型</typeparam>
    /// <param name="value">要解构的 8 元组</param>
    /// <param name="func">接收 8 个参数的函数</param>
    /// <returns>函数返回值</returns>
    public static TResult Apply<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(this (T1, T2, T3, T4, T5, T6, T7, T8) value, Func<T1, T2, T3, T4, T5, T6, T7, T8, TResult> func)
    {
        return func(value.Item1, value.Item2, value.Item3, value.Item4, value.Item5, value.Item6, value.Item7, value.Item8);
    }

    /// <summary>
    /// 将8元组解构后传入函数 (无返回值，返回原元组)
    /// </summary>
    /// <typeparam name="T1">第1个元素的类型</typeparam>
    /// <typeparam name="T2">第2个元素的类型</typeparam>
    /// <typeparam name="T3">第3个元素的类型</typeparam>
    /// <typeparam name="T4">第4个元素的类型</typeparam>
    /// <typeparam name="T5">第5个元素的类型</typeparam>
    /// <typeparam name="T6">第6个元素的类型</typeparam>
    /// <typeparam name="T7">第7个元素的类型</typeparam>
    /// <typeparam name="T8">第8个元素的类型</typeparam>
    /// <param name="value">要解构的 8 元组</param>
    /// <param name="action">接收 8 个参数的无返回值方法</param>
    /// <returns>原元组本身，便于链式调用</returns>
    public static (T1, T2, T3, T4, T5, T6, T7, T8) Apply<T1, T2, T3, T4, T5, T6, T7, T8>(this (T1, T2, T3, T4, T5, T6, T7, T8) value, Action<T1, T2, T3, T4, T5, T6, T7, T8> action)
    {
        action(value.Item1, value.Item2, value.Item3, value.Item4, value.Item5, value.Item6, value.Item7, value.Item8);
        return value;
    }

}