// <auto-generated />
namespace Canalot.Extensions;

public static partial class CanalotExtensions
{
    // 单值 Out 手写
    /// <summary>
    /// 将单个值绑定到 out 变量，并返回原值
    /// </summary>
    /// <typeparam name="T">值的类型</typeparam>
    /// <param name="value">要绑定的值</param>
    /// <param name="result">绑定的变量</param>
    /// <returns>原值本身，便于链式调用</returns>
    public static T Out<T>(this T value, out T result)
    {
        result = value;
        return value;
    }

    /// <summary>
    /// 将二元组的每个元素分别绑定到对应的 out 变量，并返回原元组
    /// </summary>
    /// <typeparam name="T1">第1个元素的类型</typeparam>
    /// <typeparam name="T2">第2个元素的类型</typeparam>
    /// <param name="value">要解构的 2 元组</param>
    /// <param name="result1">第1个值</param>
    /// <param name="result2">第2个值</param>
    /// <returns>原元组本身，便于链式调用</returns>
    public static (T1, T2) Out<T1, T2>(this (T1, T2) value, out T1 result1, out T2 result2)
    {
        (result1, result2) = value;
        return value;
    }

    /// <summary>
    /// 将3元组的每个元素分别绑定到对应的 out 变量，并返回原元组
    /// </summary>
    /// <typeparam name="T1">第1个元素的类型</typeparam>
    /// <typeparam name="T2">第2个元素的类型</typeparam>
    /// <typeparam name="T3">第3个元素的类型</typeparam>
    /// <param name="value">要解构的 3 元组</param>
    /// <param name="result1">第1个值</param>
    /// <param name="result2">第2个值</param>
    /// <param name="result3">第3个值</param>
    /// <returns>原元组本身，便于链式调用</returns>
    public static (T1, T2, T3) Out<T1, T2, T3>(this (T1, T2, T3) value, out T1 result1, out T2 result2, out T3 result3)
    {
        (result1, result2, result3) = value;
        return value;
    }

    /// <summary>
    /// 将4元组的每个元素分别绑定到对应的 out 变量，并返回原元组
    /// </summary>
    /// <typeparam name="T1">第1个元素的类型</typeparam>
    /// <typeparam name="T2">第2个元素的类型</typeparam>
    /// <typeparam name="T3">第3个元素的类型</typeparam>
    /// <typeparam name="T4">第4个元素的类型</typeparam>
    /// <param name="value">要解构的 4 元组</param>
    /// <param name="result1">第1个值</param>
    /// <param name="result2">第2个值</param>
    /// <param name="result3">第3个值</param>
    /// <param name="result4">第4个值</param>
    /// <returns>原元组本身，便于链式调用</returns>
    public static (T1, T2, T3, T4) Out<T1, T2, T3, T4>(this (T1, T2, T3, T4) value, out T1 result1, out T2 result2, out T3 result3, out T4 result4)
    {
        (result1, result2, result3, result4) = value;
        return value;
    }

    /// <summary>
    /// 将5元组的每个元素分别绑定到对应的 out 变量，并返回原元组
    /// </summary>
    /// <typeparam name="T1">第1个元素的类型</typeparam>
    /// <typeparam name="T2">第2个元素的类型</typeparam>
    /// <typeparam name="T3">第3个元素的类型</typeparam>
    /// <typeparam name="T4">第4个元素的类型</typeparam>
    /// <typeparam name="T5">第5个元素的类型</typeparam>
    /// <param name="value">要解构的 5 元组</param>
    /// <param name="result1">第1个值</param>
    /// <param name="result2">第2个值</param>
    /// <param name="result3">第3个值</param>
    /// <param name="result4">第4个值</param>
    /// <param name="result5">第5个值</param>
    /// <returns>原元组本身，便于链式调用</returns>
    public static (T1, T2, T3, T4, T5) Out<T1, T2, T3, T4, T5>(this (T1, T2, T3, T4, T5) value, out T1 result1, out T2 result2, out T3 result3, out T4 result4, out T5 result5)
    {
        (result1, result2, result3, result4, result5) = value;
        return value;
    }

    /// <summary>
    /// 将6元组的每个元素分别绑定到对应的 out 变量，并返回原元组
    /// </summary>
    /// <typeparam name="T1">第1个元素的类型</typeparam>
    /// <typeparam name="T2">第2个元素的类型</typeparam>
    /// <typeparam name="T3">第3个元素的类型</typeparam>
    /// <typeparam name="T4">第4个元素的类型</typeparam>
    /// <typeparam name="T5">第5个元素的类型</typeparam>
    /// <typeparam name="T6">第6个元素的类型</typeparam>
    /// <param name="value">要解构的 6 元组</param>
    /// <param name="result1">第1个值</param>
    /// <param name="result2">第2个值</param>
    /// <param name="result3">第3个值</param>
    /// <param name="result4">第4个值</param>
    /// <param name="result5">第5个值</param>
    /// <param name="result6">第6个值</param>
    /// <returns>原元组本身，便于链式调用</returns>
    public static (T1, T2, T3, T4, T5, T6) Out<T1, T2, T3, T4, T5, T6>(this (T1, T2, T3, T4, T5, T6) value, out T1 result1, out T2 result2, out T3 result3, out T4 result4, out T5 result5, out T6 result6)
    {
        (result1, result2, result3, result4, result5, result6) = value;
        return value;
    }

    /// <summary>
    /// 将7元组的每个元素分别绑定到对应的 out 变量，并返回原元组
    /// </summary>
    /// <typeparam name="T1">第1个元素的类型</typeparam>
    /// <typeparam name="T2">第2个元素的类型</typeparam>
    /// <typeparam name="T3">第3个元素的类型</typeparam>
    /// <typeparam name="T4">第4个元素的类型</typeparam>
    /// <typeparam name="T5">第5个元素的类型</typeparam>
    /// <typeparam name="T6">第6个元素的类型</typeparam>
    /// <typeparam name="T7">第7个元素的类型</typeparam>
    /// <param name="value">要解构的 7 元组</param>
    /// <param name="result1">第1个值</param>
    /// <param name="result2">第2个值</param>
    /// <param name="result3">第3个值</param>
    /// <param name="result4">第4个值</param>
    /// <param name="result5">第5个值</param>
    /// <param name="result6">第6个值</param>
    /// <param name="result7">第7个值</param>
    /// <returns>原元组本身，便于链式调用</returns>
    public static (T1, T2, T3, T4, T5, T6, T7) Out<T1, T2, T3, T4, T5, T6, T7>(this (T1, T2, T3, T4, T5, T6, T7) value, out T1 result1, out T2 result2, out T3 result3, out T4 result4, out T5 result5, out T6 result6, out T7 result7)
    {
        (result1, result2, result3, result4, result5, result6, result7) = value;
        return value;
    }

    /// <summary>
    /// 将8元组的每个元素分别绑定到对应的 out 变量，并返回原元组
    /// </summary>
    /// <typeparam name="T1">第1个元素的类型</typeparam>
    /// <typeparam name="T2">第2个元素的类型</typeparam>
    /// <typeparam name="T3">第3个元素的类型</typeparam>
    /// <typeparam name="T4">第4个元素的类型</typeparam>
    /// <typeparam name="T5">第5个元素的类型</typeparam>
    /// <typeparam name="T6">第6个元素的类型</typeparam>
    /// <typeparam name="T7">第7个元素的类型</typeparam>
    /// <typeparam name="T8">第8个元素的类型</typeparam>
    /// <param name="value">要解构的 8 元组</param>
    /// <param name="result1">第1个值</param>
    /// <param name="result2">第2个值</param>
    /// <param name="result3">第3个值</param>
    /// <param name="result4">第4个值</param>
    /// <param name="result5">第5个值</param>
    /// <param name="result6">第6个值</param>
    /// <param name="result7">第7个值</param>
    /// <param name="result8">第8个值</param>
    /// <returns>原元组本身，便于链式调用</returns>
    public static (T1, T2, T3, T4, T5, T6, T7, T8) Out<T1, T2, T3, T4, T5, T6, T7, T8>(this (T1, T2, T3, T4, T5, T6, T7, T8) value, out T1 result1, out T2 result2, out T3 result3, out T4 result4, out T5 result5, out T6 result6, out T7 result7, out T8 result8)
    {
        (result1, result2, result3, result4, result5, result6, result7, result8) = value;
        return value;
    }

}