// <auto-generated />
namespace Canalot.Extensions;

public static partial class CanalotExtensions
{
    // ========== 单个参数 ==========
    // 4种：T, Func<T>, Func<T,T>, Action<T>

    /// <summary>
    /// 如果条件成立，返回指定值
    /// </summary>
    public static T When<T>(this T value, bool condition, T trueValue)
    {
        return condition ? trueValue : value;
    }

    /// <summary>
    /// 如果条件成立，执行无参委托并返回结果
    /// </summary>
    public static T When<T>(this T value, bool condition, Func<T> trueFunc)
    {
        return condition ? trueFunc() : value;
    }

    /// <summary>
    /// 如果条件成立，执行转换函数并返回结果
    /// </summary>
    public static T When<T>(this T value, bool condition, Func<T, T> trueFunc)
    {
        return condition ? trueFunc(value) : value;
    }

    /// <summary>
    /// 如果条件成立，执行操作并返回原值
    /// </summary>
    public static T When<T>(this T value, bool condition, Action<T> trueAction)
    {
        if (condition)
        {
            trueAction(value);
        }
        return value;
    }

    /// <summary>
    /// 根据条件返回不同结果：成立时返回值，不成立时返回值
    /// </summary>
    public static TResult When<T, TResult>(this T value, bool condition, TResult trueValue, TResult falseValue)
    {
        if (condition)
        {
            return trueValue;
        }
        else
        {
            return falseValue;
        }
    }

    /// <summary>
    /// 根据条件返回不同结果：成立时返回值，不成立时返回无参委托
    /// </summary>
    public static TResult When<T, TResult>(this T value, bool condition, TResult trueValue, Func<TResult> falseFunc)
    {
        if (condition)
        {
            return trueValue;
        }
        else
        {
            return falseFunc();
        }
    }

    /// <summary>
    /// 根据条件返回不同结果：成立时返回值，不成立时返回有参委托
    /// </summary>
    public static TResult When<T, TResult>(this T value, bool condition, TResult trueValue, Func<T, TResult> falseFunc)
    {
        if (condition)
        {
            return trueValue;
        }
        else
        {
            return falseFunc(value);
        }
    }

    /// <summary>
    /// 根据条件返回不同结果：成立时返回无参委托，不成立时返回值
    /// </summary>
    public static TResult When<T, TResult>(this T value, bool condition, Func<TResult> trueFunc, TResult falseValue)
    {
        if (condition)
        {
            return trueFunc();
        }
        else
        {
            return falseValue;
        }
    }

    /// <summary>
    /// 根据条件返回不同结果：成立时返回无参委托，不成立时返回无参委托
    /// </summary>
    public static TResult When<T, TResult>(this T value, bool condition, Func<TResult> trueFunc, Func<TResult> falseFunc)
    {
        if (condition)
        {
            return trueFunc();
        }
        else
        {
            return falseFunc();
        }
    }

    /// <summary>
    /// 根据条件返回不同结果：成立时返回无参委托，不成立时返回有参委托
    /// </summary>
    public static TResult When<T, TResult>(this T value, bool condition, Func<TResult> trueFunc, Func<T, TResult> falseFunc)
    {
        if (condition)
        {
            return trueFunc();
        }
        else
        {
            return falseFunc(value);
        }
    }

    /// <summary>
    /// 根据条件返回不同结果：成立时返回有参委托，不成立时返回值
    /// </summary>
    public static TResult When<T, TResult>(this T value, bool condition, Func<T, TResult> trueFunc, TResult falseValue)
    {
        if (condition)
        {
            return trueFunc(value);
        }
        else
        {
            return falseValue;
        }
    }

    /// <summary>
    /// 根据条件返回不同结果：成立时返回有参委托，不成立时返回无参委托
    /// </summary>
    public static TResult When<T, TResult>(this T value, bool condition, Func<T, TResult> trueFunc, Func<TResult> falseFunc)
    {
        if (condition)
        {
            return trueFunc(value);
        }
        else
        {
            return falseFunc();
        }
    }

    /// <summary>
    /// 根据条件返回不同结果：成立时返回有参委托，不成立时返回有参委托
    /// </summary>
    public static TResult When<T, TResult>(this T value, bool condition, Func<T, TResult> trueFunc, Func<T, TResult> falseFunc)
    {
        if (condition)
        {
            return trueFunc(value);
        }
        else
        {
            return falseFunc(value);
        }
    }

    /// <summary>
    /// 根据条件执行不同操作：成立时值，不成立时操作：成立时返回值，不成立时执行操作返回原值
    /// </summary>
    public static T When<T>(this T value, bool condition, T trueValue, Action<T> falseAction)
    {
        if (condition)
        {
            return trueValue;
        }
        else
        {
            falseAction(value);
            return value;
        }
    }

    /// <summary>
    /// 根据条件执行不同操作：成立时无参委托，不成立时操作：成立时返回无参委托，不成立时执行操作返回原值
    /// </summary>
    public static T When<T>(this T value, bool condition, Func<T> trueFunc, Action<T> falseAction)
    {
        if (condition)
        {
            return trueFunc();
        }
        else
        {
            falseAction(value);
            return value;
        }
    }

    /// <summary>
    /// 根据条件执行不同操作：成立时有参委托，不成立时操作：成立时返回有参委托，不成立时执行操作返回原值
    /// </summary>
    public static T When<T>(this T value, bool condition, Func<T, T> trueFunc, Action<T> falseAction)
    {
        if (condition)
        {
            return trueFunc(value);
        }
        else
        {
            falseAction(value);
            return value;
        }
    }

    /// <summary>
    /// 根据条件执行不同操作：成立时操作，不成立时值：成立时执行操作返回原值，不成立时返回值
    /// </summary>
    public static T When<T>(this T value, bool condition, Action<T> trueAction, T falseValue)
    {
        if (condition)
        {
            trueAction(value);
            return value;
        }
        else
        {
            return falseValue;
        }
    }

    /// <summary>
    /// 根据条件执行不同操作：成立时操作，不成立时无参委托：成立时执行操作返回原值，不成立时返回无参委托
    /// </summary>
    public static T When<T>(this T value, bool condition, Action<T> trueAction, Func<T> falseFunc)
    {
        if (condition)
        {
            trueAction(value);
            return value;
        }
        else
        {
            return falseFunc();
        }
    }

    /// <summary>
    /// 根据条件执行不同操作：成立时操作，不成立时有参委托：成立时执行操作返回原值，不成立时返回有参委托
    /// </summary>
    public static T When<T>(this T value, bool condition, Action<T> trueAction, Func<T, T> falseFunc)
    {
        if (condition)
        {
            trueAction(value);
            return value;
        }
        else
        {
            return falseFunc(value);
        }
    }

    /// <summary>
    /// 根据条件执行不同操作：成立时操作，不成立时操作，均返回原值
    /// </summary>
    public static T When<T>(this T value, bool condition, Action<T> trueAction, Action<T> falseAction)
    {
        if (condition)
        {
            trueAction(value);
        }
        else
        {
            falseAction(value);
        }
        return value;
    }

}