// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

namespace Canalot.Utils; 
/// <summary>
/// 为 2 元组提供 awaiter 支持
/// </summary>
public readonly struct TupleTaskAwaiter<T1, T2> : ICriticalNotifyCompletion
{
    private readonly Task<T1> _task1;
    private readonly Task<T2> _task2;
    private readonly Task _combined;

    public TupleTaskAwaiter((Task<T1>, Task<T2>) tasks)
    {
        _task1 = tasks.Item1;
        _task2 = tasks.Item2;
        _combined = Task.WhenAll(_task1, _task2);
    }

    public bool IsCompleted => _combined.IsCompleted;

    public void OnCompleted(Action continuation) 
        => _combined.GetAwaiter().OnCompleted(continuation);

    public void UnsafeOnCompleted(Action continuation) 
        => _combined.GetAwaiter().UnsafeOnCompleted(continuation);

    public (T1, T2) GetResult()
    {
        _combined.GetAwaiter().GetResult();
        return (_task1.Result, _task2.Result);
    }
}

/// <summary>
/// 为 3 元组提供 awaiter 支持
/// </summary>
public readonly struct TupleTaskAwaiter<T1, T2, T3> : ICriticalNotifyCompletion
{
    private readonly Task<T1> _task1;
    private readonly Task<T2> _task2;
    private readonly Task<T3> _task3;
    private readonly Task _combined;

    public TupleTaskAwaiter((Task<T1>, Task<T2>, Task<T3>) tasks)
    {
        _task1 = tasks.Item1;
        _task2 = tasks.Item2;
        _task3 = tasks.Item3;
        _combined = Task.WhenAll(_task1, _task2, _task3);
    }

    public bool IsCompleted => _combined.IsCompleted;

    public void OnCompleted(Action continuation) 
        => _combined.GetAwaiter().OnCompleted(continuation);

    public void UnsafeOnCompleted(Action continuation) 
        => _combined.GetAwaiter().UnsafeOnCompleted(continuation);

    public (T1, T2, T3) GetResult()
    {
        _combined.GetAwaiter().GetResult();
        return (_task1.Result, _task2.Result, _task3.Result);
    }
}

/// <summary>
/// 为 4 元组提供 awaiter 支持
/// </summary>
public readonly struct TupleTaskAwaiter<T1, T2, T3, T4> : ICriticalNotifyCompletion
{
    private readonly Task<T1> _task1;
    private readonly Task<T2> _task2;
    private readonly Task<T3> _task3;
    private readonly Task<T4> _task4;
    private readonly Task _combined;

    public TupleTaskAwaiter((Task<T1>, Task<T2>, Task<T3>, Task<T4>) tasks)
    {
        _task1 = tasks.Item1;
        _task2 = tasks.Item2;
        _task3 = tasks.Item3;
        _task4 = tasks.Item4;
        _combined = Task.WhenAll(_task1, _task2, _task3, _task4);
    }

    public bool IsCompleted => _combined.IsCompleted;

    public void OnCompleted(Action continuation) 
        => _combined.GetAwaiter().OnCompleted(continuation);

    public void UnsafeOnCompleted(Action continuation) 
        => _combined.GetAwaiter().UnsafeOnCompleted(continuation);

    public (T1, T2, T3, T4) GetResult()
    {
        _combined.GetAwaiter().GetResult();
        return (_task1.Result, _task2.Result, _task3.Result, _task4.Result);
    }
}

/// <summary>
/// 为 5 元组提供 awaiter 支持
/// </summary>
public readonly struct TupleTaskAwaiter<T1, T2, T3, T4, T5> : ICriticalNotifyCompletion
{
    private readonly Task<T1> _task1;
    private readonly Task<T2> _task2;
    private readonly Task<T3> _task3;
    private readonly Task<T4> _task4;
    private readonly Task<T5> _task5;
    private readonly Task _combined;

    public TupleTaskAwaiter((Task<T1>, Task<T2>, Task<T3>, Task<T4>, Task<T5>) tasks)
    {
        _task1 = tasks.Item1;
        _task2 = tasks.Item2;
        _task3 = tasks.Item3;
        _task4 = tasks.Item4;
        _task5 = tasks.Item5;
        _combined = Task.WhenAll(_task1, _task2, _task3, _task4, _task5);
    }

    public bool IsCompleted => _combined.IsCompleted;

    public void OnCompleted(Action continuation) 
        => _combined.GetAwaiter().OnCompleted(continuation);

    public void UnsafeOnCompleted(Action continuation) 
        => _combined.GetAwaiter().UnsafeOnCompleted(continuation);

    public (T1, T2, T3, T4, T5) GetResult()
    {
        _combined.GetAwaiter().GetResult();
        return (_task1.Result, _task2.Result, _task3.Result, _task4.Result, _task5.Result);
    }
}

/// <summary>
/// 为 6 元组提供 awaiter 支持
/// </summary>
public readonly struct TupleTaskAwaiter<T1, T2, T3, T4, T5, T6> : ICriticalNotifyCompletion
{
    private readonly Task<T1> _task1;
    private readonly Task<T2> _task2;
    private readonly Task<T3> _task3;
    private readonly Task<T4> _task4;
    private readonly Task<T5> _task5;
    private readonly Task<T6> _task6;
    private readonly Task _combined;

    public TupleTaskAwaiter((Task<T1>, Task<T2>, Task<T3>, Task<T4>, Task<T5>, Task<T6>) tasks)
    {
        _task1 = tasks.Item1;
        _task2 = tasks.Item2;
        _task3 = tasks.Item3;
        _task4 = tasks.Item4;
        _task5 = tasks.Item5;
        _task6 = tasks.Item6;
        _combined = Task.WhenAll(_task1, _task2, _task3, _task4, _task5, _task6);
    }

    public bool IsCompleted => _combined.IsCompleted;

    public void OnCompleted(Action continuation) 
        => _combined.GetAwaiter().OnCompleted(continuation);

    public void UnsafeOnCompleted(Action continuation) 
        => _combined.GetAwaiter().UnsafeOnCompleted(continuation);

    public (T1, T2, T3, T4, T5, T6) GetResult()
    {
        _combined.GetAwaiter().GetResult();
        return (_task1.Result, _task2.Result, _task3.Result, _task4.Result, _task5.Result, _task6.Result);
    }
}

/// <summary>
/// 为 7 元组提供 awaiter 支持
/// </summary>
public readonly struct TupleTaskAwaiter<T1, T2, T3, T4, T5, T6, T7> : ICriticalNotifyCompletion
{
    private readonly Task<T1> _task1;
    private readonly Task<T2> _task2;
    private readonly Task<T3> _task3;
    private readonly Task<T4> _task4;
    private readonly Task<T5> _task5;
    private readonly Task<T6> _task6;
    private readonly Task<T7> _task7;
    private readonly Task _combined;

    public TupleTaskAwaiter((Task<T1>, Task<T2>, Task<T3>, Task<T4>, Task<T5>, Task<T6>, Task<T7>) tasks)
    {
        _task1 = tasks.Item1;
        _task2 = tasks.Item2;
        _task3 = tasks.Item3;
        _task4 = tasks.Item4;
        _task5 = tasks.Item5;
        _task6 = tasks.Item6;
        _task7 = tasks.Item7;
        _combined = Task.WhenAll(_task1, _task2, _task3, _task4, _task5, _task6, _task7);
    }

    public bool IsCompleted => _combined.IsCompleted;

    public void OnCompleted(Action continuation) 
        => _combined.GetAwaiter().OnCompleted(continuation);

    public void UnsafeOnCompleted(Action continuation) 
        => _combined.GetAwaiter().UnsafeOnCompleted(continuation);

    public (T1, T2, T3, T4, T5, T6, T7) GetResult()
    {
        _combined.GetAwaiter().GetResult();
        return (_task1.Result, _task2.Result, _task3.Result, _task4.Result, _task5.Result, _task6.Result, _task7.Result);
    }
}

 

public static partial class TupleTaskExtensions
{
    /// <summary>
    /// 获取 2 元组中所有任务的 awaiter
    /// </summary>
    public static TupleTaskAwaiter<T1, T2> GetAwaiter<T1, T2>(this (Task<T1>, Task<T2>) tasks)
        => new(tasks);

    /// <summary>
    /// 获取 3 元组中所有任务的 awaiter
    /// </summary>
    public static TupleTaskAwaiter<T1, T2, T3> GetAwaiter<T1, T2, T3>(this (Task<T1>, Task<T2>, Task<T3>) tasks)
        => new(tasks);

    /// <summary>
    /// 获取 4 元组中所有任务的 awaiter
    /// </summary>
    public static TupleTaskAwaiter<T1, T2, T3, T4> GetAwaiter<T1, T2, T3, T4>(this (Task<T1>, Task<T2>, Task<T3>, Task<T4>) tasks)
        => new(tasks);

    /// <summary>
    /// 获取 5 元组中所有任务的 awaiter
    /// </summary>
    public static TupleTaskAwaiter<T1, T2, T3, T4, T5> GetAwaiter<T1, T2, T3, T4, T5>(this (Task<T1>, Task<T2>, Task<T3>, Task<T4>, Task<T5>) tasks)
        => new(tasks);

    /// <summary>
    /// 获取 6 元组中所有任务的 awaiter
    /// </summary>
    public static TupleTaskAwaiter<T1, T2, T3, T4, T5, T6> GetAwaiter<T1, T2, T3, T4, T5, T6>(this (Task<T1>, Task<T2>, Task<T3>, Task<T4>, Task<T5>, Task<T6>) tasks)
        => new(tasks);

    /// <summary>
    /// 获取 7 元组中所有任务的 awaiter
    /// </summary>
    public static TupleTaskAwaiter<T1, T2, T3, T4, T5, T6, T7> GetAwaiter<T1, T2, T3, T4, T5, T6, T7>(this (Task<T1>, Task<T2>, Task<T3>, Task<T4>, Task<T5>, Task<T6>, Task<T7>) tasks)
        => new(tasks);

} 